language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - DEPENDENCIES=latest
    - DEPENDENCIES=oldest

install:
  - >
    echo;
    if [ "$DEPENDENCIES" = "latest" ]; then
      echo "Installing the latest dependencies";
      composer update --with-dependencies
    else
      echo "Installing the lowest dependencies";
      composer update --with-dependencies --prefer-lowest
    fi;
    composer show;

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

script:
  - >
    echo;
    echo "Validating the composer.json";
    composer validate --no-check-all --no-check-lock --strict;

  - >
    echo;
    echo "Linting all PHP files";
    composer ci:lint;

  - >
    echo;
    echo "Running the PHPUnit tests";
    composer ci:tests;
